query Repositories($login: String!, $first: Int!, $orderBy: RepositoryOrder!) {
  user(login: $login) {
    repositories(first: $first, orderBy: $orderBy) {
      nodes {
        name
        url
        description
        primaryLanguage {
          color
          name
        }
        updatedAt
        stargazerCount
        repositoryTopics(first: 10) {
          nodes {
            topic {
              name
            }
          }
        }
        forks {
          totalCount
        }
        isPrivate
      }
    }
  }
}
