query UserRepositories($login: String!, $first: Int!, $orderBy: RepositoryOrder!, $after: String) {
  user(login: $login) {
    repositories(first: $first, orderBy: $orderBy, after: $after) {
      nodes {
        name
        url
        description
        primaryLanguage {
          color
          name
        }
        updatedAt
        stargazerCount
        repositoryTopics(first: 10) {
          nodes {
            topic {
              name
            }
          }
        }
        forks {
          totalCount
        }
        isPrivate
      }
      pageInfo {
        endCursor
        startCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
}
