query Search(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $query: String!
  $type: SearchType!
  $size: Int
) {
  search(after: $after, before: $before, first: $first, last: $last, query: $query, type: $type) {
    edges {
      node {
        ... on User {
          id
          login
          name
          avatarUrl(size: $size)
          status {
            emoji
            message
          }
        }
      }
    }
  }
}
